- name: Install Homebrew formulae
  homebrew: update_homebrew=yes name={{item}} state=latest
  with_items:
    # VCS systems
    - git
    - mercurial
    - subversion
    # Github tools
    - hub
    - ghi
    # OCaml
    - objective-caml
    - opam
    # Dotfile management and system setup
    - stow
    - ansible
    # Misc tools
    - pandoc
    - nmap
    - the_silver_searcher
    - trash
    - youtube-dl
    - autojump
    - wget
    - rlwrap
- name: Install ASpell
  homebrew: name=aspell state=latest
            install_options="--with-lang-de --with-lang-en"
- name: Install Emacs
  homebrew: name=emacs state=latest
            install_options="--HEAD --use-git-head --cocoa --with-gnutls --with-rsvg --with-imagemagick"
