  osx_defaults: domain=com.apple.desktopservices name=DSDontWriteNetworkStores
                type=bool value=true
- name: Show control characters
  osx_defaults: domain=NSGlobalDomain name=NSTextShowsControlCharacters
                type=bool value=true
- name: No shadow in screenshots
  osx_defaults: domain=com.apple.screencapture name=disable-shadow
                type=bool value=true
- name: Search in current folder by default
  osx_defaults: domain=com.apple.finder name=FXDefaultSearchScope
                type=string value='SCcf'
- name: Do not warn about changing extensions
  osx_defaults: domain=com.apple.finder name=FXEnableExtensionChangeWarning
                type=bool value=false
- name: Do not warn when emptying trash
  osx_defaults: domain=com.apple.finder name=WarnOnEmptyTrash
                type=bool value=false
- name: Hide desktop icons for built-in hard disks
  osx_defaults: domain=com.apple.finder name=ShowHardDrivesOnDesktop
                type=bool value=false
- name: Show desktop icons for servers and removable media
  osx_defaults: domain=com.apple.finder name={{item}} type=bool value=true
  with_items:
    - ShowExternalHardDrivesOnDesktop
    - ShowMountedServersOnDesktop
    - ShowRemovableMediaOnDesktop
- name: Minimize windows to their apps
  osx_defaults: domain=com.apple.dock name=minimize-to-application
                type=bool value=true
- name: Show indicators for open applications
  osx_defaults: domain=com.apple.dock name=show-process-indicators
                type=bool value=true
- name: Dock to bottom
  osx_defaults: domain=com.apple.dock name=orientation type=string value=bottom
- name: Do not hide the dock automatically
  osx_defaults: domain=com.apple.dock name=autohide type=bool value=false
- name: Make hidden icons transparent
  osx_defaults: domain=com.apple.dock name=showhidden type=bool value=true
- name: Do not rearrange spaces on most recent usage
  osx_defaults: domain=com.apple.dock name=mru-spaces type=bool value=false
- name: Disable the Dashboard
  osx_defaults: domain=com.apple.dashboard name=mcx-disabled
                type=bool value=true
- name: Do not show Dashboard as a Space
  osx_defaults: domain=com.apple.dock name=dashboard-in-overlay
                type=bool value=true
- name: Disable iTunes Ping
  osx_defaults: domain=com.apple.iTunes name={{item}} type=bool value=true
  with_items:
    - disablePingSidebar
    - disablePing
