# Replace the broken in-kernel rtl8192cu module with the upstream driver from
# Realtek.  We get the driver from https://github.com/dz0ny/rt8192cu which is
# fixed for recent Kernel versions.
- name: Update the package cache
  apt: update_cache=yes cache_valid_time=0
- name: Install packages to build kernel modules
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - linux-headers-generic
    - dkms
- name: Download 8192cu
  get_url: url=https://github.com/dz0ny/rt8192cu/archive/master.tar.gz
           dest=/tmp/rt8192cu-master.tar.gz
- name: Extract 8192cu
  unarchive: src=/tmp/rt8192cu-master.tar.gz dest=/tmp/
- name: Unload broken rtl8192cu
  modprobe: name=rtl8192cu state=absent
- name: Blacklist broken rtl8192cu
  kernel_blacklist: name=rtl8192cu state=present
                    blacklist_file=/etc/modprobe.d/blacklist-rtl8192cu.conf
- name: Build and install 8192cu with DKMS
  command: make -C /tmp/rt8192cu-master dkms
- fail: msg="Please establish a network connection and re-run make ansible!"
