---
- hosts: local
  tasks:
    - group_by: key={{ ansible_distribution }}
      tags:
        - packages
        - configuration
        - setup

- hosts: MacOSX
  gather_facts: False
  vars:
    my_username: swiesner
    my_home: /Users/swiesner
    gem_executable: gem
  tasks:
    - include: tasks/osx_verify.yml
      tags: setup
    - include: tasks/common_setup.yml
      when: ansible_user_id == 'root'
      tags: setup
    - include: tasks/osx_system_setup.yml
      when: ansible_user_id == 'root'
      tags: setup
    - include: tasks/osx_packages.yml
      sudo: True
      sudo_user: "{{my_username}}"
      tags: packages
    - include: tasks/user_packages.yml
      tags: packages
      sudo: True
      sudo_user: "{{my_username}}"
    - include: tasks/osx_user_configuration.yml
      tags: configuration
      sudo: True
      sudo_user: "{{my_username}}"

- hosts: Ubuntu
  gather_facts: False
  vars:
    my_username: swiesner
    my_home: /home/swiesner
    gem_executable: gem2.0
  tasks:
    - include: tasks/ubuntu_packages.yml
      when: ansible_user_id == 'root'
      tags: packages
    - include: tasks/common_setup.yml
      when: ansible_user_id == 'root'
      tags: setup
    - include: tasks/user_packages.yml
      tags: packages
      sudo: True
      sudo_user: "{{my_username}}"
